### ISSUE TITLE
SVG 100% height not working outside of elm reactor

### ISSUE THREAD

**Issue by purei** [zaboco/elm-draggable#29]
something elm reactor is doing allows for the svg height 100% to act as expected.

however, when compiling the MultipleTargetsExample into a standalone index.html with elm make (or using elm live), the svg element (grey background) is only about 2.5 boxes in height (150 px).  tested on OS X 10.12 with firefox, chrome and safari.

apologies that this isn't an elm-draggable specific bug, but i thought i'd mention it in case there was some trivial fix.

i've googled around for svg specific problems, but svg height specific symptoms supposedly were bugfixed years ago.  in the browser debugger the computed values look similar to me; i cannot see what elm reactor does different.

to be sure i wasn't crazy, i rewrote the example to replace the Svg rects with Html divs with position absolute, and it works without issue.

**Comment by zaboco** [comment]
Yes, I've noticed that issue myself, and actually fixed it few days ago, but didn't publish a new package version until today. So it's fixed in 2.0.1.

The svg was stretched in `elm-reactor` because the html has some extra style added:
```css
html, head, body {
  margin: 0;
  height: 100%;
}
```

`elm-make` does not add this be default, you would have to compile to `js` file and use a custom `html` file (which I previously did for the `gh_pages` examples).

What I did to solve the issue was using viewport units (`height: 100vh` would fill the viewport), a css feature I've recently learned.

**Comment by purei** [comment]
odd, as i did try adding exactly those css directives in the debugger (edit style on the page you're viewing), and it didn't work.  but i only tried that in safari, and it might've be something svg specific.  i've tried as you mentioned though, and it does.  thanks!
