### ISSUE TITLE
customMouseTrigger with multiple targets

### ISSUE THREAD

**Issue by what-a-guy** [zaboco/elm-draggable#40]
This module seems to be just right for my project--very nice!  I am running into a problem, however.  Is there a way to combine customMouseTrigger (which seems to require Msg () as the 'customEnvelope') with a multiple-target application (using Msg String to identify the dragged objects)?

**Comment by zaboco** [comment]
It is actually possible, even though it's not ideal. The idea is to add an `Id` as first param to the `MouseTrigger` message.

So, assuming that we want to add more scenes in [FreeDrawingExample](https://github.com/zaboco/elm-draggable/blob/master/examples/FreeDrawingExample.elm):

```elm
type Msg = StartPathAndDrag Id (Draggable.Msg ()) Position
```

Then in the view, we trigger it with:
```elm
Draggable.customMouseTrigger mouseOffsetDecoder (StartPathAndDrag sceneId)
```

... and save the `Id` in the model as `selectedId` or something, and then use it.

Full working example, even if simplified: https://ellie-app.com/TxNsP45yB4a1/0

P.S. This is supposed to be more straightforward in a future version(#39), but that PR can't be merged yet because of some performance issues.

**Comment by what-a-guy** [comment]
Following your example, I still run into a conflict with DragMsg.  In your code, it's typed as

**DragMsg ()**

whereas I need 

**DragMsg String**

So I get a mismatch in update with StartPathAndDrag:
Function `update` is expecting the 2nd argument to be:                                                     

    Draggable.Msg String

But it is:

    Draggable.Msg ()

My update code looks like:

> StartPathAndDrag id dragMsg ( x, y ) ->
>        Draggable.update config dragMsg model

**Comment by zaboco** [comment]
Do you set the key in another way, using `mouseTrigger`?
- if **not**, you can change the type of the key (which is not used) to `()`, having `DragMsg (Draggable.Msg ())`
- if **yes**, there is a not-so-nice workaround :)

We can continue this discussion on slack, I'm zaboco. (If you haven't already joined it's at http://elmlang.herokuapp.com/)

**Comment by zaboco** [comment]
will close this, since it was resolved on slack
