### ISSUE TITLE
Possibility to set `VirtualDom.Options`

### ISSUE THREAD

**Issue by archaeron** [zaboco/elm-draggable#43]
Hey

I'd like to start with a "thank you" for this library :) 

I could really use something like:
```
customMouseTrigger : VirtualDom.Options -> Decoder a -> (Msg () -> a -> msg) -> VirtualDom.Property msg
customMouseTrigger options customDecoder customEnvelope =
    VirtualDom.onWithOptions "mousedown"
        options
        (Decode.map2 customEnvelope (positionDecoder ()) customDecoder)
```
I would build it outside of this library, but I don't have access to the `Internals` module.

**Comment by zaboco** [comment]
Hi, glad you find this library useful :).

This can be done, but the API would have to be changed quite a bit, since there is already a `customMouseTrigger`, and adding another customization would require some new way to pass options. 
What exactly is your use-case for this? Can you give a code example? Maybe we could find another way around this.

Thanks.

**Comment by archaeron** [comment]
hey :)

I've made a minimal example here:
https://ellie-app.com/4dZbyvLN4YMa1/0

You can drag the blue element around, but you can't edit the input field.
I managed to make the input field usable by setting the option from above manually.
Do you see another way to achieve the same thing?

**Comment by zaboco** [comment]
A solution would be to layout the `div` and `input` as siblings: 
https://ellie-app.com/4fcmmyMQLsra1/0

**Comment by archaeron** [comment]
@zaboco thanks, I moved stuff around with your idea and it's working :)
